//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PrismaMigrations struct {
	ID                string `sql:"primary_key"`
	Checksum          string
	FinishedAt        *time.Time
	MigrationName     string
	Logs              *string
	RolledBackAt      *time.Time
	StartedAt         time.Time
	AppliedStepsCount string
}
