//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type Customer struct {
	ID          string `sql:"primary_key"`
	Title       *string
	FirstName   *string
	MiddleName  *string
	LastName    *string
	DateOfBirth *string
	Contacts    shared.ContactField
	IsLead      bool
	Description *string
	CreatedAt   int64
	UpdatedAt   int64
}
