//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type Destination struct {
	ID          string `sql:"primary_key"`
	Name        shared.LangField
	Description shared.LangField
	ParentID    *string
	Location    shared.LocationField
	IsDeleted   bool
	IsActive    bool
	CreatedAt   int64
	UpdatedAt   int64
}
