//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type LedgerSessions struct {
	ID            string `sql:"primary_key"`
	LedgerID      string
	OpenedBy      string
	ClosedBy      *string
	OpeningAmount string
	ClosingAmount string
	Status        string
	Notes         *string
	CreatedAt     int64
	UpdatedAt     int64
}
