//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Movement struct {
	ID           string `sql:"primary_key"`
	SessionID    string
	RegisteredBy string
	Amount       float64
	Type         string
	Description  *string
	CreatedAt    int64
	UpdatedAt    int64
}
