//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Payment struct {
	ID            string `sql:"primary_key"`
	TripID        string
	CustomerID    string
	RegisteredBy  string
	MovementID    *string
	Amount        float64
	PaymentMethod string
	CreatedAt     int64
	UpdatedAt     int64
}
