//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type ResourceProvider struct {
	ID         string `sql:"primary_key"`
	ResourceID string
	ProviderID *string
	UserID     *string
	RefPrices  shared.PriceField
	CreatedAt  int64
	UpdatedAt  int64
}
