//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type Resource struct {
	ID            string `sql:"primary_key"`
	DestinationID *string
	Location      shared.LocationField
	Name          shared.LangField
	Description   shared.LangField
	Images        shared.ImageField
	IsActive      bool
	CreatedAt     int64
	UpdatedAt     int64
}
