//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type Role struct {
	ID          string `sql:"primary_key"`
	Name        string
	Description *string
	IsActive    *bool
	Permissions shared.PermissionField
	CreatedAt   int64
	UpdatedAt   int64
}
