//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type Tag struct {
	ID          string `sql:"primary_key"`
	Title       shared.LangField
	Description shared.LangField
	CreatedAt   int64
	UpdatedAt   int64
}
