//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type Tour struct {
	ID               string `sql:"primary_key"`
	Code             string
	Name             shared.LangField
	Slug             shared.LangField
	DiscountPercent  float64
	Days             int32
	GroupSize        string
	Transport        shared.LangField
	Accommodation    shared.LangField
	Team             shared.LangField
	ShortDescription shared.LangField
	LongDescription  shared.LangField
	Images           shared.ImageField
	IsPublic         bool
	IsDeleted        bool
	CreatedAt        int64
	UpdatedAt        int64
}
