//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TourResourceProvider struct {
	ID                 string `sql:"primary_key"`
	TourID             string
	TourVariantID      string
	ResourceProviderID string
	StartDate          int32
	EndDate            int32
	OriginalCost       *float64
	Currency           *string
	ProfitPercent      *float64
	DollarChangeRage   *float64
	Quantity           int32
	IsVisible          bool
	CreatedAt          int64
	UpdatedAt          int64
}
