//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/oliwallywonka/alpaca_backend/internal/shared"
)

type TourDestination struct {
	ID            string `sql:"primary_key"`
	DestinationID string
	TourID        string
	TourVariantID string
	Description   shared.LangField
	StartDate     int32
	EndDate       int32
	CreatedAt     int64
	UpdatedAt     int64
}
