//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TourVariant struct {
	ID         string `sql:"primary_key"`
	TourID     string
	MinPersons int32
	MaxPersons int32
	TotalPrice float64
	CreatedAt  int64
	UpdatedAt  int64
}
