//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TripDestination struct {
	ID            string `sql:"primary_key"`
	TripID        string
	DestinationID string
	PricePp       float64
	StartDate     int32
	EndDate       int32
}
