//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Trip struct {
	ID             string `sql:"primary_key"`
	TourID         string
	RegisteredBy   string
	CustomerID     string
	State          string
	StartDate      int32
	EndDate        int32
	AvailableSlots int32
	NumGuests      int32
	PricePp        float64
	Total          float64
	CreatedAt      int64
	UpdatedAt      int64
}
