//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TripExpense struct {
	ID          string `sql:"primary_key"`
	CreatedByID string
	TripID      string
	MovementID  *string
	Amount      float64
	Description string
	CreatedAt   int64
	UpdatedAt   int64
}
