//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CashRegister = newCashRegisterTable("", "cash_register", "")

type cashRegisterTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnString
	OwnerID   sqlite.ColumnString
	CreatedAt sqlite.ColumnInteger
	UpdatedAt sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CashRegisterTable struct {
	cashRegisterTable

	EXCLUDED cashRegisterTable
}

// AS creates new CashRegisterTable with assigned alias
func (a CashRegisterTable) AS(alias string) *CashRegisterTable {
	return newCashRegisterTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CashRegisterTable with assigned schema name
func (a CashRegisterTable) FromSchema(schemaName string) *CashRegisterTable {
	return newCashRegisterTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CashRegisterTable with assigned table prefix
func (a CashRegisterTable) WithPrefix(prefix string) *CashRegisterTable {
	return newCashRegisterTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CashRegisterTable with assigned table suffix
func (a CashRegisterTable) WithSuffix(suffix string) *CashRegisterTable {
	return newCashRegisterTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCashRegisterTable(schemaName, tableName, alias string) *CashRegisterTable {
	return &CashRegisterTable{
		cashRegisterTable: newCashRegisterTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newCashRegisterTableImpl("", "excluded", ""),
	}
}

func newCashRegisterTableImpl(schemaName, tableName, alias string) cashRegisterTable {
	var (
		IDColumn        = sqlite.StringColumn("id")
		OwnerIDColumn   = sqlite.StringColumn("owner_id")
		CreatedAtColumn = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn = sqlite.IntegerColumn("updated_at")
		allColumns      = sqlite.ColumnList{IDColumn, OwnerIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = sqlite.ColumnList{OwnerIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = sqlite.ColumnList{}
	)

	return cashRegisterTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		OwnerID:   OwnerIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
