//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Customer = newCustomerTable("", "customer", "")

type customerTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnString
	Title       sqlite.ColumnString
	FirstName   sqlite.ColumnString
	MiddleName  sqlite.ColumnString
	LastName    sqlite.ColumnString
	DateOfBirth sqlite.ColumnString
	Contacts    sqlite.ColumnString
	IsLead      sqlite.ColumnBool
	Description sqlite.ColumnString
	CreatedAt   sqlite.ColumnInteger
	UpdatedAt   sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CustomerTable struct {
	customerTable

	EXCLUDED customerTable
}

// AS creates new CustomerTable with assigned alias
func (a CustomerTable) AS(alias string) *CustomerTable {
	return newCustomerTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CustomerTable with assigned schema name
func (a CustomerTable) FromSchema(schemaName string) *CustomerTable {
	return newCustomerTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CustomerTable with assigned table prefix
func (a CustomerTable) WithPrefix(prefix string) *CustomerTable {
	return newCustomerTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CustomerTable with assigned table suffix
func (a CustomerTable) WithSuffix(suffix string) *CustomerTable {
	return newCustomerTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCustomerTable(schemaName, tableName, alias string) *CustomerTable {
	return &CustomerTable{
		customerTable: newCustomerTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newCustomerTableImpl("", "excluded", ""),
	}
}

func newCustomerTableImpl(schemaName, tableName, alias string) customerTable {
	var (
		IDColumn          = sqlite.StringColumn("id")
		TitleColumn       = sqlite.StringColumn("title")
		FirstNameColumn   = sqlite.StringColumn("first_name")
		MiddleNameColumn  = sqlite.StringColumn("middle_name")
		LastNameColumn    = sqlite.StringColumn("last_name")
		DateOfBirthColumn = sqlite.StringColumn("date_of_birth")
		ContactsColumn    = sqlite.StringColumn("contacts")
		IsLeadColumn      = sqlite.BoolColumn("is_lead")
		DescriptionColumn = sqlite.StringColumn("description")
		CreatedAtColumn   = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn   = sqlite.IntegerColumn("updated_at")
		allColumns        = sqlite.ColumnList{IDColumn, TitleColumn, FirstNameColumn, MiddleNameColumn, LastNameColumn, DateOfBirthColumn, ContactsColumn, IsLeadColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = sqlite.ColumnList{TitleColumn, FirstNameColumn, MiddleNameColumn, LastNameColumn, DateOfBirthColumn, ContactsColumn, IsLeadColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = sqlite.ColumnList{ContactsColumn, IsLeadColumn, DescriptionColumn}
	)

	return customerTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Title:       TitleColumn,
		FirstName:   FirstNameColumn,
		MiddleName:  MiddleNameColumn,
		LastName:    LastNameColumn,
		DateOfBirth: DateOfBirthColumn,
		Contacts:    ContactsColumn,
		IsLead:      IsLeadColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
