//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Destination = newDestinationTable("", "destination", "")

type destinationTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnString
	Name        sqlite.ColumnString
	Description sqlite.ColumnString
	ParentID    sqlite.ColumnString
	Location    sqlite.ColumnString
	IsDeleted   sqlite.ColumnBool
	IsActive    sqlite.ColumnBool
	CreatedAt   sqlite.ColumnInteger
	UpdatedAt   sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type DestinationTable struct {
	destinationTable

	EXCLUDED destinationTable
}

// AS creates new DestinationTable with assigned alias
func (a DestinationTable) AS(alias string) *DestinationTable {
	return newDestinationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DestinationTable with assigned schema name
func (a DestinationTable) FromSchema(schemaName string) *DestinationTable {
	return newDestinationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DestinationTable with assigned table prefix
func (a DestinationTable) WithPrefix(prefix string) *DestinationTable {
	return newDestinationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DestinationTable with assigned table suffix
func (a DestinationTable) WithSuffix(suffix string) *DestinationTable {
	return newDestinationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDestinationTable(schemaName, tableName, alias string) *DestinationTable {
	return &DestinationTable{
		destinationTable: newDestinationTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newDestinationTableImpl("", "excluded", ""),
	}
}

func newDestinationTableImpl(schemaName, tableName, alias string) destinationTable {
	var (
		IDColumn          = sqlite.StringColumn("id")
		NameColumn        = sqlite.StringColumn("name")
		DescriptionColumn = sqlite.StringColumn("description")
		ParentIDColumn    = sqlite.StringColumn("parent_id")
		LocationColumn    = sqlite.StringColumn("location")
		IsDeletedColumn   = sqlite.BoolColumn("is_deleted")
		IsActiveColumn    = sqlite.BoolColumn("is_active")
		CreatedAtColumn   = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn   = sqlite.IntegerColumn("updated_at")
		allColumns        = sqlite.ColumnList{IDColumn, NameColumn, DescriptionColumn, ParentIDColumn, LocationColumn, IsDeletedColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = sqlite.ColumnList{NameColumn, DescriptionColumn, ParentIDColumn, LocationColumn, IsDeletedColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = sqlite.ColumnList{IsDeletedColumn, IsActiveColumn}
	)

	return destinationTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		ParentID:    ParentIDColumn,
		Location:    LocationColumn,
		IsDeleted:   IsDeletedColumn,
		IsActive:    IsActiveColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
