//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var LedgerSessions = newLedgerSessionsTable("", "ledger_sessions", "")

type ledgerSessionsTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	LedgerID      sqlite.ColumnString
	OpenedBy      sqlite.ColumnString
	ClosedBy      sqlite.ColumnString
	OpeningAmount sqlite.ColumnString
	ClosingAmount sqlite.ColumnString
	Status        sqlite.ColumnString
	Notes         sqlite.ColumnString
	CreatedAt     sqlite.ColumnInteger
	UpdatedAt     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type LedgerSessionsTable struct {
	ledgerSessionsTable

	EXCLUDED ledgerSessionsTable
}

// AS creates new LedgerSessionsTable with assigned alias
func (a LedgerSessionsTable) AS(alias string) *LedgerSessionsTable {
	return newLedgerSessionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LedgerSessionsTable with assigned schema name
func (a LedgerSessionsTable) FromSchema(schemaName string) *LedgerSessionsTable {
	return newLedgerSessionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LedgerSessionsTable with assigned table prefix
func (a LedgerSessionsTable) WithPrefix(prefix string) *LedgerSessionsTable {
	return newLedgerSessionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LedgerSessionsTable with assigned table suffix
func (a LedgerSessionsTable) WithSuffix(suffix string) *LedgerSessionsTable {
	return newLedgerSessionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLedgerSessionsTable(schemaName, tableName, alias string) *LedgerSessionsTable {
	return &LedgerSessionsTable{
		ledgerSessionsTable: newLedgerSessionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newLedgerSessionsTableImpl("", "excluded", ""),
	}
}

func newLedgerSessionsTableImpl(schemaName, tableName, alias string) ledgerSessionsTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		LedgerIDColumn      = sqlite.StringColumn("ledger_id")
		OpenedByColumn      = sqlite.StringColumn("opened_by")
		ClosedByColumn      = sqlite.StringColumn("closed_by")
		OpeningAmountColumn = sqlite.StringColumn("opening_amount")
		ClosingAmountColumn = sqlite.StringColumn("closing_amount")
		StatusColumn        = sqlite.StringColumn("status")
		NotesColumn         = sqlite.StringColumn("notes")
		CreatedAtColumn     = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn     = sqlite.IntegerColumn("updated_at")
		allColumns          = sqlite.ColumnList{IDColumn, LedgerIDColumn, OpenedByColumn, ClosedByColumn, OpeningAmountColumn, ClosingAmountColumn, StatusColumn, NotesColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = sqlite.ColumnList{LedgerIDColumn, OpenedByColumn, ClosedByColumn, OpeningAmountColumn, ClosingAmountColumn, StatusColumn, NotesColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = sqlite.ColumnList{}
	)

	return ledgerSessionsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		LedgerID:      LedgerIDColumn,
		OpenedBy:      OpenedByColumn,
		ClosedBy:      ClosedByColumn,
		OpeningAmount: OpeningAmountColumn,
		ClosingAmount: ClosingAmountColumn,
		Status:        StatusColumn,
		Notes:         NotesColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
