//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Movement = newMovementTable("", "movement", "")

type movementTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnString
	SessionID    sqlite.ColumnString
	RegisteredBy sqlite.ColumnString
	Amount       sqlite.ColumnFloat
	Type         sqlite.ColumnString
	Description  sqlite.ColumnString
	CreatedAt    sqlite.ColumnInteger
	UpdatedAt    sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type MovementTable struct {
	movementTable

	EXCLUDED movementTable
}

// AS creates new MovementTable with assigned alias
func (a MovementTable) AS(alias string) *MovementTable {
	return newMovementTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MovementTable with assigned schema name
func (a MovementTable) FromSchema(schemaName string) *MovementTable {
	return newMovementTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MovementTable with assigned table prefix
func (a MovementTable) WithPrefix(prefix string) *MovementTable {
	return newMovementTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MovementTable with assigned table suffix
func (a MovementTable) WithSuffix(suffix string) *MovementTable {
	return newMovementTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMovementTable(schemaName, tableName, alias string) *MovementTable {
	return &MovementTable{
		movementTable: newMovementTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newMovementTableImpl("", "excluded", ""),
	}
}

func newMovementTableImpl(schemaName, tableName, alias string) movementTable {
	var (
		IDColumn           = sqlite.StringColumn("id")
		SessionIDColumn    = sqlite.StringColumn("session_id")
		RegisteredByColumn = sqlite.StringColumn("registered_by")
		AmountColumn       = sqlite.FloatColumn("amount")
		TypeColumn         = sqlite.StringColumn("type")
		DescriptionColumn  = sqlite.StringColumn("description")
		CreatedAtColumn    = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn    = sqlite.IntegerColumn("updated_at")
		allColumns         = sqlite.ColumnList{IDColumn, SessionIDColumn, RegisteredByColumn, AmountColumn, TypeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = sqlite.ColumnList{SessionIDColumn, RegisteredByColumn, AmountColumn, TypeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = sqlite.ColumnList{}
	)

	return movementTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SessionID:    SessionIDColumn,
		RegisteredBy: RegisteredByColumn,
		Amount:       AmountColumn,
		Type:         TypeColumn,
		Description:  DescriptionColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
