//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Payment = newPaymentTable("", "payment", "")

type paymentTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	TripID        sqlite.ColumnString
	CustomerID    sqlite.ColumnString
	RegisteredBy  sqlite.ColumnString
	MovementID    sqlite.ColumnString
	Amount        sqlite.ColumnFloat
	PaymentMethod sqlite.ColumnString
	CreatedAt     sqlite.ColumnInteger
	UpdatedAt     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type PaymentTable struct {
	paymentTable

	EXCLUDED paymentTable
}

// AS creates new PaymentTable with assigned alias
func (a PaymentTable) AS(alias string) *PaymentTable {
	return newPaymentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PaymentTable with assigned schema name
func (a PaymentTable) FromSchema(schemaName string) *PaymentTable {
	return newPaymentTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PaymentTable with assigned table prefix
func (a PaymentTable) WithPrefix(prefix string) *PaymentTable {
	return newPaymentTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PaymentTable with assigned table suffix
func (a PaymentTable) WithSuffix(suffix string) *PaymentTable {
	return newPaymentTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPaymentTable(schemaName, tableName, alias string) *PaymentTable {
	return &PaymentTable{
		paymentTable: newPaymentTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newPaymentTableImpl("", "excluded", ""),
	}
}

func newPaymentTableImpl(schemaName, tableName, alias string) paymentTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		TripIDColumn        = sqlite.StringColumn("trip_id")
		CustomerIDColumn    = sqlite.StringColumn("customer_id")
		RegisteredByColumn  = sqlite.StringColumn("registered_by")
		MovementIDColumn    = sqlite.StringColumn("movement_id")
		AmountColumn        = sqlite.FloatColumn("amount")
		PaymentMethodColumn = sqlite.StringColumn("payment_method")
		CreatedAtColumn     = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn     = sqlite.IntegerColumn("updated_at")
		allColumns          = sqlite.ColumnList{IDColumn, TripIDColumn, CustomerIDColumn, RegisteredByColumn, MovementIDColumn, AmountColumn, PaymentMethodColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = sqlite.ColumnList{TripIDColumn, CustomerIDColumn, RegisteredByColumn, MovementIDColumn, AmountColumn, PaymentMethodColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = sqlite.ColumnList{}
	)

	return paymentTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		TripID:        TripIDColumn,
		CustomerID:    CustomerIDColumn,
		RegisteredBy:  RegisteredByColumn,
		MovementID:    MovementIDColumn,
		Amount:        AmountColumn,
		PaymentMethod: PaymentMethodColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
