//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Permission = newPermissionTable("", "permission", "")

type permissionTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnString
	Name      sqlite.ColumnString
	CreatedAt sqlite.ColumnInteger
	UpdatedAt sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type PermissionTable struct {
	permissionTable

	EXCLUDED permissionTable
}

// AS creates new PermissionTable with assigned alias
func (a PermissionTable) AS(alias string) *PermissionTable {
	return newPermissionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PermissionTable with assigned schema name
func (a PermissionTable) FromSchema(schemaName string) *PermissionTable {
	return newPermissionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PermissionTable with assigned table prefix
func (a PermissionTable) WithPrefix(prefix string) *PermissionTable {
	return newPermissionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PermissionTable with assigned table suffix
func (a PermissionTable) WithSuffix(suffix string) *PermissionTable {
	return newPermissionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPermissionTable(schemaName, tableName, alias string) *PermissionTable {
	return &PermissionTable{
		permissionTable: newPermissionTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newPermissionTableImpl("", "excluded", ""),
	}
}

func newPermissionTableImpl(schemaName, tableName, alias string) permissionTable {
	var (
		IDColumn        = sqlite.StringColumn("id")
		NameColumn      = sqlite.StringColumn("name")
		CreatedAtColumn = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn = sqlite.IntegerColumn("updated_at")
		allColumns      = sqlite.ColumnList{IDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = sqlite.ColumnList{NameColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = sqlite.ColumnList{}
	)

	return permissionTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
