//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Provider = newProviderTable("", "provider", "")

type providerTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnString
	Name        sqlite.ColumnString
	Description sqlite.ColumnString
	Contacts    sqlite.ColumnString
	IsActive    sqlite.ColumnBool
	CreatedAt   sqlite.ColumnInteger
	UpdatedAt   sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ProviderTable struct {
	providerTable

	EXCLUDED providerTable
}

// AS creates new ProviderTable with assigned alias
func (a ProviderTable) AS(alias string) *ProviderTable {
	return newProviderTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProviderTable with assigned schema name
func (a ProviderTable) FromSchema(schemaName string) *ProviderTable {
	return newProviderTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProviderTable with assigned table prefix
func (a ProviderTable) WithPrefix(prefix string) *ProviderTable {
	return newProviderTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProviderTable with assigned table suffix
func (a ProviderTable) WithSuffix(suffix string) *ProviderTable {
	return newProviderTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProviderTable(schemaName, tableName, alias string) *ProviderTable {
	return &ProviderTable{
		providerTable: newProviderTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newProviderTableImpl("", "excluded", ""),
	}
}

func newProviderTableImpl(schemaName, tableName, alias string) providerTable {
	var (
		IDColumn          = sqlite.StringColumn("id")
		NameColumn        = sqlite.StringColumn("name")
		DescriptionColumn = sqlite.StringColumn("description")
		ContactsColumn    = sqlite.StringColumn("contacts")
		IsActiveColumn    = sqlite.BoolColumn("is_active")
		CreatedAtColumn   = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn   = sqlite.IntegerColumn("updated_at")
		allColumns        = sqlite.ColumnList{IDColumn, NameColumn, DescriptionColumn, ContactsColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = sqlite.ColumnList{NameColumn, DescriptionColumn, ContactsColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = sqlite.ColumnList{DescriptionColumn, ContactsColumn, IsActiveColumn}
	)

	return providerTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		Contacts:    ContactsColumn,
		IsActive:    IsActiveColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
