//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Resource = newResourceTable("", "resource", "")

type resourceTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	DestinationID sqlite.ColumnString
	Location      sqlite.ColumnString
	Name          sqlite.ColumnString
	Description   sqlite.ColumnString
	Images        sqlite.ColumnString
	IsActive      sqlite.ColumnBool
	CreatedAt     sqlite.ColumnInteger
	UpdatedAt     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ResourceTable struct {
	resourceTable

	EXCLUDED resourceTable
}

// AS creates new ResourceTable with assigned alias
func (a ResourceTable) AS(alias string) *ResourceTable {
	return newResourceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ResourceTable with assigned schema name
func (a ResourceTable) FromSchema(schemaName string) *ResourceTable {
	return newResourceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ResourceTable with assigned table prefix
func (a ResourceTable) WithPrefix(prefix string) *ResourceTable {
	return newResourceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ResourceTable with assigned table suffix
func (a ResourceTable) WithSuffix(suffix string) *ResourceTable {
	return newResourceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newResourceTable(schemaName, tableName, alias string) *ResourceTable {
	return &ResourceTable{
		resourceTable: newResourceTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newResourceTableImpl("", "excluded", ""),
	}
}

func newResourceTableImpl(schemaName, tableName, alias string) resourceTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		DestinationIDColumn = sqlite.StringColumn("destination_id")
		LocationColumn      = sqlite.StringColumn("location")
		NameColumn          = sqlite.StringColumn("name")
		DescriptionColumn   = sqlite.StringColumn("description")
		ImagesColumn        = sqlite.StringColumn("images")
		IsActiveColumn      = sqlite.BoolColumn("is_active")
		CreatedAtColumn     = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn     = sqlite.IntegerColumn("updated_at")
		allColumns          = sqlite.ColumnList{IDColumn, DestinationIDColumn, LocationColumn, NameColumn, DescriptionColumn, ImagesColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = sqlite.ColumnList{DestinationIDColumn, LocationColumn, NameColumn, DescriptionColumn, ImagesColumn, IsActiveColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = sqlite.ColumnList{ImagesColumn, IsActiveColumn}
	)

	return resourceTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		DestinationID: DestinationIDColumn,
		Location:      LocationColumn,
		Name:          NameColumn,
		Description:   DescriptionColumn,
		Images:        ImagesColumn,
		IsActive:      IsActiveColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
