//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ResourceType = newResourceTypeTable("", "resource_type", "")

type resourceTypeTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnString
	Type sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ResourceTypeTable struct {
	resourceTypeTable

	EXCLUDED resourceTypeTable
}

// AS creates new ResourceTypeTable with assigned alias
func (a ResourceTypeTable) AS(alias string) *ResourceTypeTable {
	return newResourceTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ResourceTypeTable with assigned schema name
func (a ResourceTypeTable) FromSchema(schemaName string) *ResourceTypeTable {
	return newResourceTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ResourceTypeTable with assigned table prefix
func (a ResourceTypeTable) WithPrefix(prefix string) *ResourceTypeTable {
	return newResourceTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ResourceTypeTable with assigned table suffix
func (a ResourceTypeTable) WithSuffix(suffix string) *ResourceTypeTable {
	return newResourceTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newResourceTypeTable(schemaName, tableName, alias string) *ResourceTypeTable {
	return &ResourceTypeTable{
		resourceTypeTable: newResourceTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newResourceTypeTableImpl("", "excluded", ""),
	}
}

func newResourceTypeTableImpl(schemaName, tableName, alias string) resourceTypeTable {
	var (
		IDColumn       = sqlite.StringColumn("id")
		TypeColumn     = sqlite.StringColumn("type")
		allColumns     = sqlite.ColumnList{IDColumn, TypeColumn}
		mutableColumns = sqlite.ColumnList{TypeColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return resourceTypeTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Type: TypeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
