//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ResourceResourceType = newResourceResourceTypeTable("", "resource_resource_type", "")

type resourceResourceTypeTable struct {
	sqlite.Table

	// Columns
	ID         sqlite.ColumnString
	ResourceID sqlite.ColumnString
	TypeID     sqlite.ColumnString
	CreatedAt  sqlite.ColumnInteger
	UpdatedAt  sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ResourceResourceTypeTable struct {
	resourceResourceTypeTable

	EXCLUDED resourceResourceTypeTable
}

// AS creates new ResourceResourceTypeTable with assigned alias
func (a ResourceResourceTypeTable) AS(alias string) *ResourceResourceTypeTable {
	return newResourceResourceTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ResourceResourceTypeTable with assigned schema name
func (a ResourceResourceTypeTable) FromSchema(schemaName string) *ResourceResourceTypeTable {
	return newResourceResourceTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ResourceResourceTypeTable with assigned table prefix
func (a ResourceResourceTypeTable) WithPrefix(prefix string) *ResourceResourceTypeTable {
	return newResourceResourceTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ResourceResourceTypeTable with assigned table suffix
func (a ResourceResourceTypeTable) WithSuffix(suffix string) *ResourceResourceTypeTable {
	return newResourceResourceTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newResourceResourceTypeTable(schemaName, tableName, alias string) *ResourceResourceTypeTable {
	return &ResourceResourceTypeTable{
		resourceResourceTypeTable: newResourceResourceTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newResourceResourceTypeTableImpl("", "excluded", ""),
	}
}

func newResourceResourceTypeTableImpl(schemaName, tableName, alias string) resourceResourceTypeTable {
	var (
		IDColumn         = sqlite.StringColumn("id")
		ResourceIDColumn = sqlite.StringColumn("resource_id")
		TypeIDColumn     = sqlite.StringColumn("type_id")
		CreatedAtColumn  = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn  = sqlite.IntegerColumn("updated_at")
		allColumns       = sqlite.ColumnList{IDColumn, ResourceIDColumn, TypeIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = sqlite.ColumnList{ResourceIDColumn, TypeIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = sqlite.ColumnList{}
	)

	return resourceResourceTypeTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		ResourceID: ResourceIDColumn,
		TypeID:     TypeIDColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
