//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ResourceProvider = newResourceProviderTable("", "resource_provider", "")

type resourceProviderTable struct {
	sqlite.Table

	// Columns
	ID         sqlite.ColumnString
	ResourceID sqlite.ColumnString
	ProviderID sqlite.ColumnString
	UserID     sqlite.ColumnString
	RefPrices  sqlite.ColumnString
	CreatedAt  sqlite.ColumnInteger
	UpdatedAt  sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ResourceProviderTable struct {
	resourceProviderTable

	EXCLUDED resourceProviderTable
}

// AS creates new ResourceProviderTable with assigned alias
func (a ResourceProviderTable) AS(alias string) *ResourceProviderTable {
	return newResourceProviderTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ResourceProviderTable with assigned schema name
func (a ResourceProviderTable) FromSchema(schemaName string) *ResourceProviderTable {
	return newResourceProviderTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ResourceProviderTable with assigned table prefix
func (a ResourceProviderTable) WithPrefix(prefix string) *ResourceProviderTable {
	return newResourceProviderTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ResourceProviderTable with assigned table suffix
func (a ResourceProviderTable) WithSuffix(suffix string) *ResourceProviderTable {
	return newResourceProviderTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newResourceProviderTable(schemaName, tableName, alias string) *ResourceProviderTable {
	return &ResourceProviderTable{
		resourceProviderTable: newResourceProviderTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newResourceProviderTableImpl("", "excluded", ""),
	}
}

func newResourceProviderTableImpl(schemaName, tableName, alias string) resourceProviderTable {
	var (
		IDColumn         = sqlite.StringColumn("id")
		ResourceIDColumn = sqlite.StringColumn("resource_id")
		ProviderIDColumn = sqlite.StringColumn("provider_id")
		UserIDColumn     = sqlite.StringColumn("user_id")
		RefPricesColumn  = sqlite.StringColumn("ref_prices")
		CreatedAtColumn  = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn  = sqlite.IntegerColumn("updated_at")
		allColumns       = sqlite.ColumnList{IDColumn, ResourceIDColumn, ProviderIDColumn, UserIDColumn, RefPricesColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = sqlite.ColumnList{ResourceIDColumn, ProviderIDColumn, UserIDColumn, RefPricesColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = sqlite.ColumnList{RefPricesColumn}
	)

	return resourceProviderTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		ResourceID: ResourceIDColumn,
		ProviderID: ProviderIDColumn,
		UserID:     UserIDColumn,
		RefPrices:  RefPricesColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
