//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Role = newRoleTable("", "role", "")

type roleTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnString
	Name        sqlite.ColumnString
	Description sqlite.ColumnString
	IsActive    sqlite.ColumnBool
	Permissions sqlite.ColumnString
	CreatedAt   sqlite.ColumnInteger
	UpdatedAt   sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RoleTable struct {
	roleTable

	EXCLUDED roleTable
}

// AS creates new RoleTable with assigned alias
func (a RoleTable) AS(alias string) *RoleTable {
	return newRoleTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RoleTable with assigned schema name
func (a RoleTable) FromSchema(schemaName string) *RoleTable {
	return newRoleTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RoleTable with assigned table prefix
func (a RoleTable) WithPrefix(prefix string) *RoleTable {
	return newRoleTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RoleTable with assigned table suffix
func (a RoleTable) WithSuffix(suffix string) *RoleTable {
	return newRoleTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRoleTable(schemaName, tableName, alias string) *RoleTable {
	return &RoleTable{
		roleTable: newRoleTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newRoleTableImpl("", "excluded", ""),
	}
}

func newRoleTableImpl(schemaName, tableName, alias string) roleTable {
	var (
		IDColumn          = sqlite.StringColumn("id")
		NameColumn        = sqlite.StringColumn("name")
		DescriptionColumn = sqlite.StringColumn("description")
		IsActiveColumn    = sqlite.BoolColumn("is_active")
		PermissionsColumn = sqlite.StringColumn("permissions")
		CreatedAtColumn   = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn   = sqlite.IntegerColumn("updated_at")
		allColumns        = sqlite.ColumnList{IDColumn, NameColumn, DescriptionColumn, IsActiveColumn, PermissionsColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = sqlite.ColumnList{NameColumn, DescriptionColumn, IsActiveColumn, PermissionsColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = sqlite.ColumnList{DescriptionColumn, IsActiveColumn, PermissionsColumn}
	)

	return roleTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		IsActive:    IsActiveColumn,
		Permissions: PermissionsColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
