//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var SectionDescription = newSectionDescriptionTable("", "section_description", "")

type sectionDescriptionTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	TourVariantID sqlite.ColumnString
	TourID        sqlite.ColumnString
	Images        sqlite.ColumnString
	Description   sqlite.ColumnString
	StartDate     sqlite.ColumnInteger
	EndDate       sqlite.ColumnInteger
	CreatedAt     sqlite.ColumnInteger
	UpdatedAt     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type SectionDescriptionTable struct {
	sectionDescriptionTable

	EXCLUDED sectionDescriptionTable
}

// AS creates new SectionDescriptionTable with assigned alias
func (a SectionDescriptionTable) AS(alias string) *SectionDescriptionTable {
	return newSectionDescriptionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SectionDescriptionTable with assigned schema name
func (a SectionDescriptionTable) FromSchema(schemaName string) *SectionDescriptionTable {
	return newSectionDescriptionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SectionDescriptionTable with assigned table prefix
func (a SectionDescriptionTable) WithPrefix(prefix string) *SectionDescriptionTable {
	return newSectionDescriptionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SectionDescriptionTable with assigned table suffix
func (a SectionDescriptionTable) WithSuffix(suffix string) *SectionDescriptionTable {
	return newSectionDescriptionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSectionDescriptionTable(schemaName, tableName, alias string) *SectionDescriptionTable {
	return &SectionDescriptionTable{
		sectionDescriptionTable: newSectionDescriptionTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newSectionDescriptionTableImpl("", "excluded", ""),
	}
}

func newSectionDescriptionTableImpl(schemaName, tableName, alias string) sectionDescriptionTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		TourVariantIDColumn = sqlite.StringColumn("tour_variant_id")
		TourIDColumn        = sqlite.StringColumn("tour_id")
		ImagesColumn        = sqlite.StringColumn("images")
		DescriptionColumn   = sqlite.StringColumn("description")
		StartDateColumn     = sqlite.IntegerColumn("startDate")
		EndDateColumn       = sqlite.IntegerColumn("endDate")
		CreatedAtColumn     = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn     = sqlite.IntegerColumn("updated_at")
		allColumns          = sqlite.ColumnList{IDColumn, TourVariantIDColumn, TourIDColumn, ImagesColumn, DescriptionColumn, StartDateColumn, EndDateColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = sqlite.ColumnList{TourVariantIDColumn, TourIDColumn, ImagesColumn, DescriptionColumn, StartDateColumn, EndDateColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = sqlite.ColumnList{ImagesColumn, StartDateColumn, EndDateColumn}
	)

	return sectionDescriptionTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		TourVariantID: TourVariantIDColumn,
		TourID:        TourIDColumn,
		Images:        ImagesColumn,
		Description:   DescriptionColumn,
		StartDate:     StartDateColumn,
		EndDate:       EndDateColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
