//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	CashRegister = CashRegister.FromSchema(schema)
	Customer = Customer.FromSchema(schema)
	Destination = Destination.FromSchema(schema)
	LedgerSessions = LedgerSessions.FromSchema(schema)
	Movement = Movement.FromSchema(schema)
	Payment = Payment.FromSchema(schema)
	Permission = Permission.FromSchema(schema)
	Provider = Provider.FromSchema(schema)
	Resource = Resource.FromSchema(schema)
	ResourceProvider = ResourceProvider.FromSchema(schema)
	ResourceResourceType = ResourceResourceType.FromSchema(schema)
	ResourceType = ResourceType.FromSchema(schema)
	Role = Role.FromSchema(schema)
	SectionDescription = SectionDescription.FromSchema(schema)
	Tag = Tag.FromSchema(schema)
	Tour = Tour.FromSchema(schema)
	TourDestination = TourDestination.FromSchema(schema)
	TourResourceProvider = TourResourceProvider.FromSchema(schema)
	TourTag = TourTag.FromSchema(schema)
	TourVariant = TourVariant.FromSchema(schema)
	Trip = Trip.FromSchema(schema)
	TripDestination = TripDestination.FromSchema(schema)
	TripExpense = TripExpense.FromSchema(schema)
	TripResource = TripResource.FromSchema(schema)
	User = User.FromSchema(schema)
}
