//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Tour = newTourTable("", "tour", "")

type tourTable struct {
	sqlite.Table

	// Columns
	ID               sqlite.ColumnString
	Code             sqlite.ColumnString
	Name             sqlite.ColumnString
	Slug             sqlite.ColumnString
	DiscountPercent  sqlite.ColumnFloat
	Days             sqlite.ColumnInteger
	GroupSize        sqlite.ColumnString
	Transport        sqlite.ColumnString
	Accommodation    sqlite.ColumnString
	Team             sqlite.ColumnString
	ShortDescription sqlite.ColumnString
	LongDescription  sqlite.ColumnString
	Images           sqlite.ColumnString
	IsPublic         sqlite.ColumnBool
	IsDeleted        sqlite.ColumnBool
	CreatedAt        sqlite.ColumnInteger
	UpdatedAt        sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TourTable struct {
	tourTable

	EXCLUDED tourTable
}

// AS creates new TourTable with assigned alias
func (a TourTable) AS(alias string) *TourTable {
	return newTourTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TourTable with assigned schema name
func (a TourTable) FromSchema(schemaName string) *TourTable {
	return newTourTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TourTable with assigned table prefix
func (a TourTable) WithPrefix(prefix string) *TourTable {
	return newTourTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TourTable with assigned table suffix
func (a TourTable) WithSuffix(suffix string) *TourTable {
	return newTourTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTourTable(schemaName, tableName, alias string) *TourTable {
	return &TourTable{
		tourTable: newTourTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newTourTableImpl("", "excluded", ""),
	}
}

func newTourTableImpl(schemaName, tableName, alias string) tourTable {
	var (
		IDColumn               = sqlite.StringColumn("id")
		CodeColumn             = sqlite.StringColumn("code")
		NameColumn             = sqlite.StringColumn("name")
		SlugColumn             = sqlite.StringColumn("slug")
		DiscountPercentColumn  = sqlite.FloatColumn("discount_percent")
		DaysColumn             = sqlite.IntegerColumn("days")
		GroupSizeColumn        = sqlite.StringColumn("group_size")
		TransportColumn        = sqlite.StringColumn("transport")
		AccommodationColumn    = sqlite.StringColumn("accommodation")
		TeamColumn             = sqlite.StringColumn("team")
		ShortDescriptionColumn = sqlite.StringColumn("short_description")
		LongDescriptionColumn  = sqlite.StringColumn("long_description")
		ImagesColumn           = sqlite.StringColumn("images")
		IsPublicColumn         = sqlite.BoolColumn("is_public")
		IsDeletedColumn        = sqlite.BoolColumn("is_deleted")
		CreatedAtColumn        = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn        = sqlite.IntegerColumn("updated_at")
		allColumns             = sqlite.ColumnList{IDColumn, CodeColumn, NameColumn, SlugColumn, DiscountPercentColumn, DaysColumn, GroupSizeColumn, TransportColumn, AccommodationColumn, TeamColumn, ShortDescriptionColumn, LongDescriptionColumn, ImagesColumn, IsPublicColumn, IsDeletedColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns         = sqlite.ColumnList{CodeColumn, NameColumn, SlugColumn, DiscountPercentColumn, DaysColumn, GroupSizeColumn, TransportColumn, AccommodationColumn, TeamColumn, ShortDescriptionColumn, LongDescriptionColumn, ImagesColumn, IsPublicColumn, IsDeletedColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns         = sqlite.ColumnList{DiscountPercentColumn, DaysColumn, GroupSizeColumn, ImagesColumn, IsPublicColumn, IsDeletedColumn}
	)

	return tourTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		Code:             CodeColumn,
		Name:             NameColumn,
		Slug:             SlugColumn,
		DiscountPercent:  DiscountPercentColumn,
		Days:             DaysColumn,
		GroupSize:        GroupSizeColumn,
		Transport:        TransportColumn,
		Accommodation:    AccommodationColumn,
		Team:             TeamColumn,
		ShortDescription: ShortDescriptionColumn,
		LongDescription:  LongDescriptionColumn,
		Images:           ImagesColumn,
		IsPublic:         IsPublicColumn,
		IsDeleted:        IsDeletedColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
