//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TourDestination = newTourDestinationTable("", "tour_destination", "")

type tourDestinationTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	DestinationID sqlite.ColumnString
	TourID        sqlite.ColumnString
	TourVariantID sqlite.ColumnString
	Description   sqlite.ColumnString
	StartDate     sqlite.ColumnInteger
	EndDate       sqlite.ColumnInteger
	CreatedAt     sqlite.ColumnInteger
	UpdatedAt     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TourDestinationTable struct {
	tourDestinationTable

	EXCLUDED tourDestinationTable
}

// AS creates new TourDestinationTable with assigned alias
func (a TourDestinationTable) AS(alias string) *TourDestinationTable {
	return newTourDestinationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TourDestinationTable with assigned schema name
func (a TourDestinationTable) FromSchema(schemaName string) *TourDestinationTable {
	return newTourDestinationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TourDestinationTable with assigned table prefix
func (a TourDestinationTable) WithPrefix(prefix string) *TourDestinationTable {
	return newTourDestinationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TourDestinationTable with assigned table suffix
func (a TourDestinationTable) WithSuffix(suffix string) *TourDestinationTable {
	return newTourDestinationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTourDestinationTable(schemaName, tableName, alias string) *TourDestinationTable {
	return &TourDestinationTable{
		tourDestinationTable: newTourDestinationTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newTourDestinationTableImpl("", "excluded", ""),
	}
}

func newTourDestinationTableImpl(schemaName, tableName, alias string) tourDestinationTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		DestinationIDColumn = sqlite.StringColumn("destination_id")
		TourIDColumn        = sqlite.StringColumn("tour_id")
		TourVariantIDColumn = sqlite.StringColumn("tour_variant_id")
		DescriptionColumn   = sqlite.StringColumn("description")
		StartDateColumn     = sqlite.IntegerColumn("startDate")
		EndDateColumn       = sqlite.IntegerColumn("endDate")
		CreatedAtColumn     = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn     = sqlite.IntegerColumn("updated_at")
		allColumns          = sqlite.ColumnList{IDColumn, DestinationIDColumn, TourIDColumn, TourVariantIDColumn, DescriptionColumn, StartDateColumn, EndDateColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = sqlite.ColumnList{DestinationIDColumn, TourIDColumn, TourVariantIDColumn, DescriptionColumn, StartDateColumn, EndDateColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = sqlite.ColumnList{StartDateColumn, EndDateColumn}
	)

	return tourDestinationTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		DestinationID: DestinationIDColumn,
		TourID:        TourIDColumn,
		TourVariantID: TourVariantIDColumn,
		Description:   DescriptionColumn,
		StartDate:     StartDateColumn,
		EndDate:       EndDateColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
