//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TourVariant = newTourVariantTable("", "tour_variant", "")

type tourVariantTable struct {
	sqlite.Table

	// Columns
	ID         sqlite.ColumnString
	TourID     sqlite.ColumnString
	MinPersons sqlite.ColumnInteger
	MaxPersons sqlite.ColumnInteger
	TotalPrice sqlite.ColumnFloat
	CreatedAt  sqlite.ColumnInteger
	UpdatedAt  sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TourVariantTable struct {
	tourVariantTable

	EXCLUDED tourVariantTable
}

// AS creates new TourVariantTable with assigned alias
func (a TourVariantTable) AS(alias string) *TourVariantTable {
	return newTourVariantTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TourVariantTable with assigned schema name
func (a TourVariantTable) FromSchema(schemaName string) *TourVariantTable {
	return newTourVariantTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TourVariantTable with assigned table prefix
func (a TourVariantTable) WithPrefix(prefix string) *TourVariantTable {
	return newTourVariantTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TourVariantTable with assigned table suffix
func (a TourVariantTable) WithSuffix(suffix string) *TourVariantTable {
	return newTourVariantTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTourVariantTable(schemaName, tableName, alias string) *TourVariantTable {
	return &TourVariantTable{
		tourVariantTable: newTourVariantTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTourVariantTableImpl("", "excluded", ""),
	}
}

func newTourVariantTableImpl(schemaName, tableName, alias string) tourVariantTable {
	var (
		IDColumn         = sqlite.StringColumn("id")
		TourIDColumn     = sqlite.StringColumn("tour_id")
		MinPersonsColumn = sqlite.IntegerColumn("min_persons")
		MaxPersonsColumn = sqlite.IntegerColumn("max_persons")
		TotalPriceColumn = sqlite.FloatColumn("totalPrice")
		CreatedAtColumn  = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn  = sqlite.IntegerColumn("updated_at")
		allColumns       = sqlite.ColumnList{IDColumn, TourIDColumn, MinPersonsColumn, MaxPersonsColumn, TotalPriceColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = sqlite.ColumnList{TourIDColumn, MinPersonsColumn, MaxPersonsColumn, TotalPriceColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = sqlite.ColumnList{TotalPriceColumn}
	)

	return tourVariantTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		TourID:     TourIDColumn,
		MinPersons: MinPersonsColumn,
		MaxPersons: MaxPersonsColumn,
		TotalPrice: TotalPriceColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
