//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TourTag = newTourTagTable("", "tour_tag", "")

type tourTagTable struct {
	sqlite.Table

	// Columns
	ID     sqlite.ColumnString
	TourID sqlite.ColumnString
	TagID  sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TourTagTable struct {
	tourTagTable

	EXCLUDED tourTagTable
}

// AS creates new TourTagTable with assigned alias
func (a TourTagTable) AS(alias string) *TourTagTable {
	return newTourTagTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TourTagTable with assigned schema name
func (a TourTagTable) FromSchema(schemaName string) *TourTagTable {
	return newTourTagTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TourTagTable with assigned table prefix
func (a TourTagTable) WithPrefix(prefix string) *TourTagTable {
	return newTourTagTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TourTagTable with assigned table suffix
func (a TourTagTable) WithSuffix(suffix string) *TourTagTable {
	return newTourTagTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTourTagTable(schemaName, tableName, alias string) *TourTagTable {
	return &TourTagTable{
		tourTagTable: newTourTagTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newTourTagTableImpl("", "excluded", ""),
	}
}

func newTourTagTableImpl(schemaName, tableName, alias string) tourTagTable {
	var (
		IDColumn       = sqlite.StringColumn("id")
		TourIDColumn   = sqlite.StringColumn("tour_id")
		TagIDColumn    = sqlite.StringColumn("tag_id")
		allColumns     = sqlite.ColumnList{IDColumn, TourIDColumn, TagIDColumn}
		mutableColumns = sqlite.ColumnList{TourIDColumn, TagIDColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return tourTagTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:     IDColumn,
		TourID: TourIDColumn,
		TagID:  TagIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
