//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TourResourceProvider = newTourResourceProviderTable("", "tour_resource_provider", "")

type tourResourceProviderTable struct {
	sqlite.Table

	// Columns
	ID                 sqlite.ColumnString
	TourID             sqlite.ColumnString
	TourVariantID      sqlite.ColumnString
	ResourceProviderID sqlite.ColumnString
	StartDate          sqlite.ColumnInteger
	EndDate            sqlite.ColumnInteger
	OriginalCost       sqlite.ColumnFloat
	Currency           sqlite.ColumnString
	ProfitPercent      sqlite.ColumnFloat
	DollarChangeRage   sqlite.ColumnFloat
	Quantity           sqlite.ColumnInteger
	IsVisible          sqlite.ColumnBool
	CreatedAt          sqlite.ColumnInteger
	UpdatedAt          sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TourResourceProviderTable struct {
	tourResourceProviderTable

	EXCLUDED tourResourceProviderTable
}

// AS creates new TourResourceProviderTable with assigned alias
func (a TourResourceProviderTable) AS(alias string) *TourResourceProviderTable {
	return newTourResourceProviderTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TourResourceProviderTable with assigned schema name
func (a TourResourceProviderTable) FromSchema(schemaName string) *TourResourceProviderTable {
	return newTourResourceProviderTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TourResourceProviderTable with assigned table prefix
func (a TourResourceProviderTable) WithPrefix(prefix string) *TourResourceProviderTable {
	return newTourResourceProviderTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TourResourceProviderTable with assigned table suffix
func (a TourResourceProviderTable) WithSuffix(suffix string) *TourResourceProviderTable {
	return newTourResourceProviderTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTourResourceProviderTable(schemaName, tableName, alias string) *TourResourceProviderTable {
	return &TourResourceProviderTable{
		tourResourceProviderTable: newTourResourceProviderTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newTourResourceProviderTableImpl("", "excluded", ""),
	}
}

func newTourResourceProviderTableImpl(schemaName, tableName, alias string) tourResourceProviderTable {
	var (
		IDColumn                 = sqlite.StringColumn("id")
		TourIDColumn             = sqlite.StringColumn("tour_id")
		TourVariantIDColumn      = sqlite.StringColumn("tour_variant_id")
		ResourceProviderIDColumn = sqlite.StringColumn("resource_provider_id")
		StartDateColumn          = sqlite.IntegerColumn("startDate")
		EndDateColumn            = sqlite.IntegerColumn("endDate")
		OriginalCostColumn       = sqlite.FloatColumn("original_cost")
		CurrencyColumn           = sqlite.StringColumn("currency")
		ProfitPercentColumn      = sqlite.FloatColumn("profit_percent")
		DollarChangeRageColumn   = sqlite.FloatColumn("dollar_change_rage")
		QuantityColumn           = sqlite.IntegerColumn("quantity")
		IsVisibleColumn          = sqlite.BoolColumn("is_visible")
		CreatedAtColumn          = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn          = sqlite.IntegerColumn("updated_at")
		allColumns               = sqlite.ColumnList{IDColumn, TourIDColumn, TourVariantIDColumn, ResourceProviderIDColumn, StartDateColumn, EndDateColumn, OriginalCostColumn, CurrencyColumn, ProfitPercentColumn, DollarChangeRageColumn, QuantityColumn, IsVisibleColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = sqlite.ColumnList{TourIDColumn, TourVariantIDColumn, ResourceProviderIDColumn, StartDateColumn, EndDateColumn, OriginalCostColumn, CurrencyColumn, ProfitPercentColumn, DollarChangeRageColumn, QuantityColumn, IsVisibleColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = sqlite.ColumnList{StartDateColumn, EndDateColumn, QuantityColumn, IsVisibleColumn}
	)

	return tourResourceProviderTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		TourID:             TourIDColumn,
		TourVariantID:      TourVariantIDColumn,
		ResourceProviderID: ResourceProviderIDColumn,
		StartDate:          StartDateColumn,
		EndDate:            EndDateColumn,
		OriginalCost:       OriginalCostColumn,
		Currency:           CurrencyColumn,
		ProfitPercent:      ProfitPercentColumn,
		DollarChangeRage:   DollarChangeRageColumn,
		Quantity:           QuantityColumn,
		IsVisible:          IsVisibleColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
