//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TripResource = newTripResourceTable("", "trip_resource", "")

type tripResourceTable struct {
	sqlite.Table

	// Columns
	ID         sqlite.ColumnString
	TripID     sqlite.ColumnString
	ResourceID sqlite.ColumnString
	MovementID sqlite.ColumnString
	Total      sqlite.ColumnFloat
	StartDate  sqlite.ColumnInteger
	EndDate    sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TripResourceTable struct {
	tripResourceTable

	EXCLUDED tripResourceTable
}

// AS creates new TripResourceTable with assigned alias
func (a TripResourceTable) AS(alias string) *TripResourceTable {
	return newTripResourceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TripResourceTable with assigned schema name
func (a TripResourceTable) FromSchema(schemaName string) *TripResourceTable {
	return newTripResourceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TripResourceTable with assigned table prefix
func (a TripResourceTable) WithPrefix(prefix string) *TripResourceTable {
	return newTripResourceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TripResourceTable with assigned table suffix
func (a TripResourceTable) WithSuffix(suffix string) *TripResourceTable {
	return newTripResourceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTripResourceTable(schemaName, tableName, alias string) *TripResourceTable {
	return &TripResourceTable{
		tripResourceTable: newTripResourceTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newTripResourceTableImpl("", "excluded", ""),
	}
}

func newTripResourceTableImpl(schemaName, tableName, alias string) tripResourceTable {
	var (
		IDColumn         = sqlite.StringColumn("id")
		TripIDColumn     = sqlite.StringColumn("trip_id")
		ResourceIDColumn = sqlite.StringColumn("resource_id")
		MovementIDColumn = sqlite.StringColumn("movement_id")
		TotalColumn      = sqlite.FloatColumn("total")
		StartDateColumn  = sqlite.IntegerColumn("start_date")
		EndDateColumn    = sqlite.IntegerColumn("end_date")
		allColumns       = sqlite.ColumnList{IDColumn, TripIDColumn, ResourceIDColumn, MovementIDColumn, TotalColumn, StartDateColumn, EndDateColumn}
		mutableColumns   = sqlite.ColumnList{TripIDColumn, ResourceIDColumn, MovementIDColumn, TotalColumn, StartDateColumn, EndDateColumn}
		defaultColumns   = sqlite.ColumnList{}
	)

	return tripResourceTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		TripID:     TripIDColumn,
		ResourceID: ResourceIDColumn,
		MovementID: MovementIDColumn,
		Total:      TotalColumn,
		StartDate:  StartDateColumn,
		EndDate:    EndDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
