//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TripExpense = newTripExpenseTable("", "trip_expense", "")

type tripExpenseTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnString
	CreatedByID sqlite.ColumnString
	TripID      sqlite.ColumnString
	MovementID  sqlite.ColumnString
	Amount      sqlite.ColumnFloat
	Description sqlite.ColumnString
	CreatedAt   sqlite.ColumnInteger
	UpdatedAt   sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TripExpenseTable struct {
	tripExpenseTable

	EXCLUDED tripExpenseTable
}

// AS creates new TripExpenseTable with assigned alias
func (a TripExpenseTable) AS(alias string) *TripExpenseTable {
	return newTripExpenseTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TripExpenseTable with assigned schema name
func (a TripExpenseTable) FromSchema(schemaName string) *TripExpenseTable {
	return newTripExpenseTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TripExpenseTable with assigned table prefix
func (a TripExpenseTable) WithPrefix(prefix string) *TripExpenseTable {
	return newTripExpenseTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TripExpenseTable with assigned table suffix
func (a TripExpenseTable) WithSuffix(suffix string) *TripExpenseTable {
	return newTripExpenseTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTripExpenseTable(schemaName, tableName, alias string) *TripExpenseTable {
	return &TripExpenseTable{
		tripExpenseTable: newTripExpenseTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTripExpenseTableImpl("", "excluded", ""),
	}
}

func newTripExpenseTableImpl(schemaName, tableName, alias string) tripExpenseTable {
	var (
		IDColumn          = sqlite.StringColumn("id")
		CreatedByIDColumn = sqlite.StringColumn("created_by_id")
		TripIDColumn      = sqlite.StringColumn("trip_id")
		MovementIDColumn  = sqlite.StringColumn("movement_id")
		AmountColumn      = sqlite.FloatColumn("amount")
		DescriptionColumn = sqlite.StringColumn("description")
		CreatedAtColumn   = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn   = sqlite.IntegerColumn("updated_at")
		allColumns        = sqlite.ColumnList{IDColumn, CreatedByIDColumn, TripIDColumn, MovementIDColumn, AmountColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = sqlite.ColumnList{CreatedByIDColumn, TripIDColumn, MovementIDColumn, AmountColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = sqlite.ColumnList{}
	)

	return tripExpenseTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CreatedByID: CreatedByIDColumn,
		TripID:      TripIDColumn,
		MovementID:  MovementIDColumn,
		Amount:      AmountColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
