//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var TripDestination = newTripDestinationTable("", "trip_destination", "")

type tripDestinationTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	TripID        sqlite.ColumnString
	DestinationID sqlite.ColumnString
	PricePp       sqlite.ColumnFloat
	StartDate     sqlite.ColumnInteger
	EndDate       sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TripDestinationTable struct {
	tripDestinationTable

	EXCLUDED tripDestinationTable
}

// AS creates new TripDestinationTable with assigned alias
func (a TripDestinationTable) AS(alias string) *TripDestinationTable {
	return newTripDestinationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TripDestinationTable with assigned schema name
func (a TripDestinationTable) FromSchema(schemaName string) *TripDestinationTable {
	return newTripDestinationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TripDestinationTable with assigned table prefix
func (a TripDestinationTable) WithPrefix(prefix string) *TripDestinationTable {
	return newTripDestinationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TripDestinationTable with assigned table suffix
func (a TripDestinationTable) WithSuffix(suffix string) *TripDestinationTable {
	return newTripDestinationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTripDestinationTable(schemaName, tableName, alias string) *TripDestinationTable {
	return &TripDestinationTable{
		tripDestinationTable: newTripDestinationTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newTripDestinationTableImpl("", "excluded", ""),
	}
}

func newTripDestinationTableImpl(schemaName, tableName, alias string) tripDestinationTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		TripIDColumn        = sqlite.StringColumn("trip_id")
		DestinationIDColumn = sqlite.StringColumn("destination_id")
		PricePpColumn       = sqlite.FloatColumn("price_pp")
		StartDateColumn     = sqlite.IntegerColumn("start_date")
		EndDateColumn       = sqlite.IntegerColumn("end_date")
		allColumns          = sqlite.ColumnList{IDColumn, TripIDColumn, DestinationIDColumn, PricePpColumn, StartDateColumn, EndDateColumn}
		mutableColumns      = sqlite.ColumnList{TripIDColumn, DestinationIDColumn, PricePpColumn, StartDateColumn, EndDateColumn}
		defaultColumns      = sqlite.ColumnList{}
	)

	return tripDestinationTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		TripID:        TripIDColumn,
		DestinationID: DestinationIDColumn,
		PricePp:       PricePpColumn,
		StartDate:     StartDateColumn,
		EndDate:       EndDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
