//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Trip = newTripTable("", "trip", "")

type tripTable struct {
	sqlite.Table

	// Columns
	ID             sqlite.ColumnString
	TourID         sqlite.ColumnString
	RegisteredBy   sqlite.ColumnString
	CustomerID     sqlite.ColumnString
	State          sqlite.ColumnString
	StartDate      sqlite.ColumnInteger
	EndDate        sqlite.ColumnInteger
	AvailableSlots sqlite.ColumnInteger
	NumGuests      sqlite.ColumnInteger
	PricePp        sqlite.ColumnFloat
	Total          sqlite.ColumnFloat
	CreatedAt      sqlite.ColumnInteger
	UpdatedAt      sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type TripTable struct {
	tripTable

	EXCLUDED tripTable
}

// AS creates new TripTable with assigned alias
func (a TripTable) AS(alias string) *TripTable {
	return newTripTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TripTable with assigned schema name
func (a TripTable) FromSchema(schemaName string) *TripTable {
	return newTripTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TripTable with assigned table prefix
func (a TripTable) WithPrefix(prefix string) *TripTable {
	return newTripTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TripTable with assigned table suffix
func (a TripTable) WithSuffix(suffix string) *TripTable {
	return newTripTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTripTable(schemaName, tableName, alias string) *TripTable {
	return &TripTable{
		tripTable: newTripTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newTripTableImpl("", "excluded", ""),
	}
}

func newTripTableImpl(schemaName, tableName, alias string) tripTable {
	var (
		IDColumn             = sqlite.StringColumn("id")
		TourIDColumn         = sqlite.StringColumn("tour_id")
		RegisteredByColumn   = sqlite.StringColumn("registered_by")
		CustomerIDColumn     = sqlite.StringColumn("customer_id")
		StateColumn          = sqlite.StringColumn("state")
		StartDateColumn      = sqlite.IntegerColumn("start_date")
		EndDateColumn        = sqlite.IntegerColumn("end_date")
		AvailableSlotsColumn = sqlite.IntegerColumn("available_slots")
		NumGuestsColumn      = sqlite.IntegerColumn("num_guests")
		PricePpColumn        = sqlite.FloatColumn("price_pp")
		TotalColumn          = sqlite.FloatColumn("total")
		CreatedAtColumn      = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn      = sqlite.IntegerColumn("updated_at")
		allColumns           = sqlite.ColumnList{IDColumn, TourIDColumn, RegisteredByColumn, CustomerIDColumn, StateColumn, StartDateColumn, EndDateColumn, AvailableSlotsColumn, NumGuestsColumn, PricePpColumn, TotalColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = sqlite.ColumnList{TourIDColumn, RegisteredByColumn, CustomerIDColumn, StateColumn, StartDateColumn, EndDateColumn, AvailableSlotsColumn, NumGuestsColumn, PricePpColumn, TotalColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = sqlite.ColumnList{StateColumn}
	)

	return tripTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		TourID:         TourIDColumn,
		RegisteredBy:   RegisteredByColumn,
		CustomerID:     CustomerIDColumn,
		State:          StateColumn,
		StartDate:      StartDateColumn,
		EndDate:        EndDateColumn,
		AvailableSlots: AvailableSlotsColumn,
		NumGuests:      NumGuestsColumn,
		PricePp:        PricePpColumn,
		Total:          TotalColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
