//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var User = newUserTable("", "user", "")

type userTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnString
	RoleID    sqlite.ColumnString
	Email     sqlite.ColumnString
	Password  sqlite.ColumnString
	Name      sqlite.ColumnString
	Image     sqlite.ColumnString
	Contacts  sqlite.ColumnString
	CreatedAt sqlite.ColumnInteger
	UpdatedAt sqlite.ColumnInteger
	IsActive  sqlite.ColumnBool

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type UserTable struct {
	userTable

	EXCLUDED userTable
}

// AS creates new UserTable with assigned alias
func (a UserTable) AS(alias string) *UserTable {
	return newUserTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserTable with assigned schema name
func (a UserTable) FromSchema(schemaName string) *UserTable {
	return newUserTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserTable with assigned table prefix
func (a UserTable) WithPrefix(prefix string) *UserTable {
	return newUserTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserTable with assigned table suffix
func (a UserTable) WithSuffix(suffix string) *UserTable {
	return newUserTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserTable(schemaName, tableName, alias string) *UserTable {
	return &UserTable{
		userTable: newUserTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newUserTableImpl("", "excluded", ""),
	}
}

func newUserTableImpl(schemaName, tableName, alias string) userTable {
	var (
		IDColumn        = sqlite.StringColumn("id")
		RoleIDColumn    = sqlite.StringColumn("role_id")
		EmailColumn     = sqlite.StringColumn("email")
		PasswordColumn  = sqlite.StringColumn("password")
		NameColumn      = sqlite.StringColumn("name")
		ImageColumn     = sqlite.StringColumn("image")
		ContactsColumn  = sqlite.StringColumn("contacts")
		CreatedAtColumn = sqlite.IntegerColumn("created_at")
		UpdatedAtColumn = sqlite.IntegerColumn("updated_at")
		IsActiveColumn  = sqlite.BoolColumn("is_active")
		allColumns      = sqlite.ColumnList{IDColumn, RoleIDColumn, EmailColumn, PasswordColumn, NameColumn, ImageColumn, ContactsColumn, CreatedAtColumn, UpdatedAtColumn, IsActiveColumn}
		mutableColumns  = sqlite.ColumnList{RoleIDColumn, EmailColumn, PasswordColumn, NameColumn, ImageColumn, ContactsColumn, CreatedAtColumn, UpdatedAtColumn, IsActiveColumn}
		defaultColumns  = sqlite.ColumnList{ContactsColumn, IsActiveColumn}
	)

	return userTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		RoleID:    RoleIDColumn,
		Email:     EmailColumn,
		Password:  PasswordColumn,
		Name:      NameColumn,
		Image:     ImageColumn,
		Contacts:  ContactsColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		IsActive:  IsActiveColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
